name: Master Build Daily
on:
  schedule:
  - cron: "0 0 * * *"
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Run Tests
      run: dotnet test