name: Publish NuGet

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Run Tests
      run: dotnet test -m
    - name: Deploy NuGet Package
      run: dotnet nuget push ../../Nhl.Api/Nhl.Api/Nhl.Api/bin/Release/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
